### PR TITLE
Improve argurments support

### PR DESCRIPTION
**Pull request by AlirezaTheH**
Fixed bugs mentioned in #59 and also added some other minor improvements for better arguments support.

### CODE REVIEW

**Comment by AlirezaTheH** [comment]
@ewels

**Comment by AlirezaTheH** [comment]
Hi @ewels @zmoon taranlu-houzz, is there anyone to review and merge this?

**Comment by ewels** [comment]
Sorry, I'm on holiday at the moment and lost track of this. I'll try to find a spare few minutes one evening.

**Review by ewels — APPROVED** [review]
Tested locally and works great! I made a couple of minor tweaks (dedicated style flag, changeling entry etc) but nothing major.

Thanks for this!

**Pull request merged**
