### PR TITLE
Import as

### PR DESCRIPTION
**Pull request by ewels**
Start playing with the `import rich_click as click` concept suggested by @willmcgugan in #8

### CODE REVIEW

**Comment by ewels** [comment]
Hmm, did a speed back-of-the-car attempt just now @willmcgugan (I'm away travelling this weekend 😅) but no dice. Any ideas?

**Comment by willmcgugan** [comment]
That looks like it should work. Were you getting any errors?

**Comment by ewels** [comment]
No errors, but just default click behaviour - no customisation.

I need to import click but I guess the custom rich-click imports aren't overwriting those classes for some reason? I guess I could sort of do monkey-patching in this file to make it work 🤔

**Comment by ewels** [comment]
eg. Running the [minimal example](https://github.com/ewels/rich-click/blob/import-as/examples/03_simple_importas.py), just get the default click output:

```console
$ python examples/03_simple_importas.py
Usage: 03_simple_importas.py [OPTIONS] COMMAND [ARGS]...

  My amazing tool does all the things.

  This is a minimal example based on documentation from the 'click' package.

  You can try using --help at the top level and also for specific group
  subcommands.

Options:
  -d, --debug / -n, --no-debug  Enable debug mode
  --help                        Show this message and exit.

Commands:
  download  Pretend to download some files from somewhere
  sync      Synchronise all your files between two places
```

I've tried a few things by trial and error, but I can't get the `rich-click` objects to be used with this method. I think I need a Python wizard with more skills than I have.. 👀

**Comment by ewels** [comment]
Ok I can get it to work if do this in the `__init__.py`:

```python
from click import *
from .rich_click import rich_format_help

Group.format_help = rich_format_help
Command.format_help = rich_format_help
```

Then the `import rich_click as click` works nicely. Definitely an improvement for the end-user (less typing, less to get wrong), but it's still monkey patching - just in a different place. Which is kind of what we were trying to avoid with this...

I'll leave this open a little longer in case anyone has any ideas why the sequential import doesn't overwrite the class names in the way I expect, but if not I'll merge with this change.

**Comment by grst** [comment]
I don't think the current approach can work, as `click` never get's to know that there's a new `Group` and `Command` class in `rich_click`. 

You could try something along the lines of:

`__init__.py`:

```python
from click import * 
from .rich_click import rich_format_help
from .rich_click import Group
from .rich_click import Command

def group(*args, cls=Group, **kwargs):
    from click import group as group_
    return group_(*args, cls=cls, **kwargs)
```

**Comment by grst** [comment]
> We are again overwriting things in the click namespace, either way.

I wouldn't say so. My example only modifies the `rich_click` namespace.
So if a user did

```python
import click as cl
import rich_click as rcl
```

they could still use

```python
@cl.command()
def cli():
   pass

@rcl.command()
def cli2():
   pass
```

and one would be rich-click formatted and the other not. Whereas with monkey-patching, both would be rich-click formatted.

**Comment by ewels** [comment]
> Whereas with monkey-patching, both would be rich-click formatted.

Is that true even when we're doing the monkey patching _within_ the `rich-click` package? As in https://github.com/ewels/rich-click/pull/10#issuecomment-1040870373 ?

**Comment by ewels** [comment]
Damn, just tried it and you're right. Even when I do `Command.format_help = rich_format_help` within the `rich_click/__init__.py` it affects the class with the vanilla `import click as cl` import 😞

**Comment by grst** [comment]
> However, if you try to get the help for a command within a group it uses the default click handling still.

There's a `command_class` attribute, it seems: 
https://github.com/pallets/click/blob/49164faca678dd476f1b11a2584fd0e1c6be70b2/src/click/core.py#L1757-L1762

Maybe it's possible to set it as keyword argument:
```python
return rich_group(*args, cls=cls, command_class=cls, **kwargs)
```

Otherwise it should be possible to override it in the `Group` class.

**Comment by ewels** [comment]
ok awesome, just need to figure out how to handle the help now (`ClickException.show`). Need to run now..

**Comment by ewels** [comment]
I'm not sure that we're going to be able to get at the error message printing code any way other than monkey patching the exception classes.. :/

Code is [nestled in the `main()` function](https://github.com/pallets/click/blob/c63c70dabd3f86ca68678b4f00951f78f52d0270/src/click/core.py#L1067-L1071):

```python
except ClickException as e:
    if not standalone_mode:
        raise
    e.show()
    sys.exit(e.exit_code)
```

I don't really fancy trying to replicate the massive `main()` function so I'm not sure that there's really any other way.. Unless anyone else has any smart ideas? 👀

**Comment by grst** [comment]
Looks tough! I can't think of any better way either.

**Comment by ewels** [comment]
Figured it out 💥 43842174adfa83a6945e61df474346142cb03359

Click hops about all over the place but managed to track back to the `main()` function call and override `standalone_mode` so that it allows the exceptions to raise. Then we can catch them with our custom code and handle the output nicely 🚀

**Pull request merged**
