### PR TITLE
add context_settings support

### LINKED ISSUE #18: options inherited from context settings aren't applied
Thanks for the library, love that its a drop in replacement

Just creating this to track this here/let you know. 

Defaults set in [context settings](https://click.palletsprojects.com/en/8.0.x/api/#click.Command) aren't detected by command/groups

Minimal example:

```python
import os

USE_RICH = "USE_RICH" in os.environ

if USE_RICH:
    import rich_click as click  # type: ignore[import]
else:
    import click  # type: ignore[no-redef]

DEFAULT_CONTEXT_SETTINGS = {"show_default": True}


@click.command(context_settings=DEFAULT_CONTEXT_SETTINGS)
@click.option("--use-context-settings", default="should work", help="help text shows")
@click.option("--overwrite-to-succeed", default="does work", show_default=True, help="shows here too")
def main(use_context_settings, overwrite_to_succeed) -> None:
    click.echo(use_context_settings)
    click.echo(overwrite_to_succeed)

if __name__ == "__main__":
    main()
```

image

Would be willing to create a PR for this at some point in the future, I would imagine one just has to look these up in the parent context instead of just checking the parameters passed, but may be a bit more complicated than that...

### PR DESCRIPTION
**Pull request by dwreeves**
# Overview

- Resolves #18.
- Implements test cases that enforce this behavior. Note that Click 8.0 is not technically covered by tests, only the latest versions of Click 7 and 8 are covered.

The issue suggests there may be more issues with `context_settings` options not being passed into Rich-Click properly, but as far as I can tell, the only outstanding issue with `context_settings` was the `show_default` option.

# Behaviors of each Click version

When it comes to handling defaults using `context_settings={"show_default": True}`, each supported minor version of click, 7, 8.0, and 8.1, behaves differently.

In the below sub-sections, I catalog each behavior of each version of Click and show that my changes to Rich-Click adhere to the behaviors of the base Click versions.

## Click 7.x

### Original Click behavior

```
>>> pip install -U "click<8" >/dev/null 2>&1 && python tests/fixtures/context_settings.py --help
Usage: context_settings.py [OPTIONS]

  Test cases for context_settings.

  Note that in click < 8.1, '[default: False]' shows for "--help".

Options:
  --a TEXT  This works in all supported click versions.  [default: show me
            always]

  --b TEXT  This works in all supported click versions.  [default: show me
            always]

  --c TEXT  Hide default only in click>=8.1  [default: show me in old
            versions]

  --d TEXT  Show 'default: (show me in c8+)' in click>=8.0. In click 7, no
            default is shown.

  --help    Show this message and exit.  [default: False]
```

### Rich-Click behavior

```
>>> pip install -U "click<8" >/dev/null 2>&1 && python tests/fixtures/context_settings.py --help
                                                                                                                                                                             
 Usage: context_settings.py [OPTIONS]                                                                                                                                        
                                                                                                                                                                             
 Test cases for context_settings.                                                                                                                                            
 Note that in click < 8.1, '[default: False]' shows for "--help".                                                                                                            
                                                                                                                                                                             
╭─ Options ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --a       TEXT  This works in all supported click versions. [default: show me always]                                                                                     │
│ --b       TEXT  This works in all supported click versions. [default: show me always]                                                                                     │
│ --c       TEXT  Hide default only in click>=8.1 [default: show me in old versions]                                                                                        │
│ --d       TEXT  Show 'default: (show me in c8+)' in click>=8.0. In click 7, no default is shown.                                                                          │
│ --help          Show this message and exit. [default: False]                                                                                                              │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

## Click 8.0

### Original Click behavior

```
>>> pip install -U "click==8.0.*" >/dev/null 2>&1 && python tests/fixtures/context_settings.py --help
Usage: context_settings.py [OPTIONS]

  Test cases for context_settings.

  Note that in click < 8.1, '[default: False]' shows for "--help".

Options:
  --a TEXT  This works in all supported click versions.  [default: show me
            always]
  --b TEXT  This works in all supported click versions.  [default: show me
            always]
  --c TEXT  Hide default only in click>=8.1  [default: show me in old
            versions]
  --d TEXT  Show 'default: (show me in c8+)' in click>=8.0. In click 7, no
            default is shown.  [default: (show me in c8+)]
  --help    Show this message and exit.  [default: False]
```

### Rich-Click behavior

```
>>> pip install -U "click==8.0.*" >/dev/null 2>&1 && python tests/fixtures/context_settings.py --help

Usage: context_settings.py [OPTIONS]                                                                                                                                        
                                                                                                                                                                            
Test cases for context_settings.                                                                                                                                            
Note that in click < 8.1, '[default: False]' shows for "--help".                                                                                                            
                                                                                                                                                                            
╭─ Options ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --a       TEXT  This works in all supported click versions. [default: show me always]                                                                                     │
│ --b       TEXT  This works in all supported click versions. [default: show me always]                                                                                     │
│ --c       TEXT  Hide default only in click>=8.1 [default: show me in old versions]                                                                                        │
│ --d       TEXT  Show 'default: (show me in c8+)' in click>=8.0. In click 7, no default is shown. [default: (show me in c8+)]                                              │
│ --help          Show this message and exit. [default: False]                                                                                                              │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

## Click 8.1

### Original Click behavior

```
>>> pip install -U "click==8.1.*" >/dev/null 2>&1 && python tests/fixtures/context_settings.py --help
Usage: context_settings.py [OPTIONS]

  Test cases for context_settings.

  Note that in click < 8.1, '[default: False]' shows for "--help".

Options:
  --a TEXT  This works in all supported click versions.  [default: show me
            always]
  --b TEXT  This works in all supported click versions.  [default: show me
            always]
  --c TEXT  Hide default only in click>=8.1
  --d TEXT  Show 'default: (show me in c8+)' in click>=8.0. In click 7, no
            default is shown.  [default: (show me in c8+)]
  --help    Show this message and exit.
```

### Rich-Click behavior

```
>>> pip install -U "click==8.1.*" >/dev/null 2>&1 && python tests/fixtures/context_settings.py --help

Usage: context_settings.py [OPTIONS]                                                                                                                                        
                                                                                                                                                                            
Test cases for context_settings.                                                                                                                                            
Note that in click < 8.1, '[default: False]' shows for "--help".                                                                                                            
                                                                                                                                                                            
╭─ Options ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --a       TEXT  This works in all supported click versions. [default: show me always]                                                                                     │
│ --b       TEXT  This works in all supported click versions. [default: show me always]                                                                                     │
│ --c       TEXT  Hide default only in click>=8.1                                                                                                                           │
│ --d       TEXT  Show 'default: (show me in c8+)' in click>=8.0. In click 7, no default is shown. [default: (show me in c8+)]                                              │
│ --help          Show this message and exit.                                                                                                                               │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

### CODE REVIEW

**Comment by dwreeves** [comment]
OK, that took a few attempts to get the CI passing, but it's ready! 😄 @ewels

**Comment by dwreeves** [comment]
@ewels This is going to conflict a little bit with the other PR because this one is using the (deprecated!!!!) distutils package (which will be removed in Python 3.12!!!), and the other one is using the suggested `packaging` package. I'll get to this as soon as I can, probably not tonight but possibly tomorrow.

**Comment by ewels** [comment]
Ah right, sorry! But yeah, I think as you say it's good to switch over anyway.

**Comment by dwreeves** [comment]
Some changes to the code between July and now:

- Had some time to think about this: I'm longer using the `packaging` package because I want to reduce the scope of dependencies; just parsing the string should be fine!
- `click` is deprecating `click.__version__` in 9.1 and is saying to use `importlib.metadata.version('click')` instead, so I switched to that.

Of course, the main point of this PR is to address #18, which we do! It is just entwined in the version compatibility stuff due to how Click 7.x, 8.0, and 8.1+ all parse things differently than one another.

**Pull request merged**
